import Head from "next/head";
import { useState } from "react";
import QRCode from "react-qr-code";
import Link from "next/link";
import { GoHomeFill } from "react-icons/go";
import QRCodeSVG from "qrcode";

export default function Generate() {
  const [qrCodeValue, setQrCodeValue] = useState("โปรดใส่ชื่อโปรเจค");

  const downloadQRCode = async () => {
    if (!qrCodeValue) {
      console.error("No QR Code value provided for download");
      return;
    }

    try {
      const url = await QRCodeSVG.toDataURL(qrCodeValue);
      const link = document.createElement("a");
      link.href = url;
      link.download = `QRCode-${new Date().toISOString()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Error generating QR code for download:', error);
    }
  };

  return (
    <>
      <Head>
        <title>Generate QR code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen justify-center text-center">
        <div className="flex flex-col justify-center items-center">
          <h1 className="text-4xl font-bold mb-6">Generate QR</h1>
          {qrCodeValue !== "" && <QRCode value={qrCodeValue} className="mb-6" />}
          <input
            className="border border-gray-400 p-2 rounded-lg"
            onChange={(e) => setQrCodeValue(e.target.value)}
            placeholder="ใส่ชื่อโปรเจค"
          />
          <button
            onClick={downloadQRCode}
            className="m-4 text-md rounded-md px-4 py-2 bg-orange-500 text-white transition-colors"
          >
            Download QR Code
          </button>
          <Link
            href="/"
            className="m-4 text-md rounded-md px-4 py-2 hover:underline"
          >
            <GoHomeFill size={50} color="black" />
          </Link>
        </div>
      </main>
    </>
  );
}
