import React, { useState, useRef, useEffect } from "react";
import { QrReader } from "react-qr-reader";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { GoHomeFill } from "react-icons/go";

export default function Scan() {
  const router = useRouter();
  const [data, setData] = useState("No result");
  const [showModal, setShowModal] = useState(false);
  const qrRef = useRef(null);
  

  const handleScan = (result, error) => {
    if (result) {
      setData(result.text);
      setShowModal(true);
      qrRef.current?.stop();
    }

    if (error) {
      console.info(error);
    }
  };

  const handleCloseModal = () => {
    setShowModal(false);
    router.reload();
  };

  const handleOK = async () => {
    router.push({
      pathname: '/process',
      query: { data: data },
    });
  };


  return (
    <>
      <Head>
        <title>QR Scan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-orange-500 h-screen flex flex-col justify-center items-center">
        <div className="flex flex-col justify-center items-center">
          <h1 className="text-4xl font-bold text-white">Scan QR code</h1>
          <div>
            <QrReader
              className=" h-[300px] w-[300px]"
              onResult={handleScan}
              constraints={{ facingMode: "environment" }}
              style={{ width: "40%", height: "40%" }}
              ref={qrRef}
            />
          </div>
          <Link
            href={`/`}
            className=" m-4 text-md rounded-full px-4 py-2 hover:underline"
          >
            <GoHomeFill size={50} color="white" />
          </Link>
          {showModal && (
            <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
              <div className="flex gap-2 justify-center flex-col bg-white rounded-md p-4">
                <p className="text-center font-bold text-xl">{data}</p>
                <button
                  className="bg-orange-500 h-12 text-white flex justify-center items-center rounded-md"
                  onClick={handleOK}
                >
                  ตรวจสอบ
                </button>
                <button
                  className="bg-gray-200 h-12 text-gray-800 rounded-md"
                  onClick={handleCloseModal}
                >
                  ยกเลิก
                </button>
              </div>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
